# Generated by Django 2.2.19 on 2023-04-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='childes',
            field=models.ManyToManyField(related_name='menu_childes', to='menu.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_parent', to='menu.Menu'),
        ),
    ]
