# Generated by Django 2.2.19 on 2023-04-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='level',
        ),
        migrations.AddField(
            model_name='menu',
            name='first_level',
            field=models.BooleanField(blank=True, null=True, verbose_name='Главный'),
        ),
    ]
