# Generated by Django 2.2.19 on 2023-04-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20230414_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='childes',
            field=models.ManyToManyField(blank=True, null=True, related_name='menu_childes', to='menu.Menu'),
        ),
    ]
