# Generated by Django 2.2.19 on 2023-04-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20230415_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.CharField(default=1, max_length=256, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
